Task/WG-61-Vite environments for local development
TACC-Cloud/hazmapper pull request #132
Opened 2023-04-10 20:22 UTC by iamthatian

## Overview: ##
This is an attempt to add environments in the react code using the `vite` build system.

On build/run, `vite` will read the `.env` file

This behavior is defined in `vite.config.ts`.

#### .ENV
And the `GEOAPI_BACKEND`  defined in `.env` will determine the target backend for local development. So, one would now have to edit the `.env` file instead of the `environments.ts` to test.

I've also included the `JWT` inside the `.env` and there is an `.env.example` for reference (`.env` is included in `.gitignore`).

#### Environment Variables
The environment variables defined in `vite.config.ts` will be exposed in the react code directly via an ~__ENV__ const (e.g. `__ENV__.apiUrl`).~ Changed to `process.env` (it seems to be this is generally compatible with tests (like jest), otherwise, because of [vite's build process](https://jestjs.io/docs/29.1/getting-started#using-vite) the `defines` are not picked up by jest, so I've opted to use `process.env` convention)

This interface is set in `src/vite.env.d.ts` for intellisense.

#### Concerns
~One concern is that now the running environment is not dynamically determined by the hostname on runtime (e.g. `hazmapper.local` or `hazmapper.utexas.edu`) and is predetermined with the prefix. I haven't thought of any issues during the build process. Would there be some cases this could be problematic? 

Another concern with this is with local development. So, we might have to enforce `hazmapper.local` instead of `localhost` for the correct `clientId`.~
Only for local development for now.

## PR Status: ##

* [X] Ready.
* [ ] Work in Progress.
* [ ] Hold.

## Related Jira tickets: ##

[WG-61](https://jira.tacc.utexas.edu/browse/WG-61)

## Summary of Changes: ##

## Testing Steps: ##
1. Copy the `.env.example` to `.env` in the `JWT`, `GEOAPI_BACKEND`, (to `development`) in `.env`.
2. Ensure that `npm run dev` works.
3. Go to http://hazmapper.local:4200.
4. Ensure that you see the local `apiUrl` display correctly next to **Menu** and that environment variables are accessible via `process.env`.

## UI Photos:

N/A

2023-04-13 03:58 UTC, nathanfranklin requested changes
I like the idea 👍   gonna discuss the staging/prod approach in slack.

I left some initial comments but getting this error when running `npm run dev ` or `npm run build:local`

```failed to load config from /Users/nathanf/dev/hazmapper/react/vite.config.ts
error during build:
Error: Unsupported Type
    at getApiUrl (file:///Users/nathanf/dev/hazmapper/react/vite.config.ts.timestamp-1681358144738.mjs:12:11)
    at file:///Users/nathanf/dev/hazmapper/react/vite.config.ts.timestamp-1681358144738.mjs:61:18
    at loadConfigFromFile (file:///Users/nathanf/dev/hazmapper/react/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:63023:15)
    at async resolveConfig (file:///Users/nathanf/dev/hazmapper/react/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:62643:28)
    at async doBuild (file:///Users/nathanf/dev/hazmapper/react/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:45554:20)
    at async build (file:///Users/nathanf/dev/hazmapper/react/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:45543:16)
    at async CAC.<anonymous> (file:///Users/nathanf/dev/hazmapper/react/node_modules/vite/dist/node/cli.js:756:9)```

2023-04-13 03:58 UTC, nathanfranklin commented on react/vite.config.ts
> +function getApiUrl(backend: string): string {
I think should be renamed `getGeoApiUrl` and add a comment

2023-04-13 03:58 UTC, nathanfranklin commented on react/vite.config.ts
> +function getPortalUrl(backend: string): string {
rename to something more explicit like getDesignSafePortalUrl?

maybe add comment?

2023-04-13 03:58 UTC, nathanfranklin commented on react/src/vite-env.d.ts
> +  portalUrl: string;
i think these should be more explicit as both are used as apis and we got so many portals out there. how about:

apiUrl -> geoApiUrl
portalUrl -> designSafePortalUrl

2023-04-13 03:58 UTC, nathanfranklin commented on react/vite.config.ts
> +    env.mapillaryClientSecret =
can you check these mapillary values?  looks the same as prod?

2023-04-13 03:58 UTC, nathanfranklin commented on react/src/vite-env.d.ts
> +  jwt: string;
jwt will need to also handle null: `string | null;`

2023-04-13 03:58 UTC, nathanfranklin commented on README.md
> +Then, for local development, the `BACKEND` specified in `.env` will allow testing different backends.
should we split this BACKEND variable into two different ones:
* GEOAPI_BACKEND
* DESIGNSAFE_PORTAL

maybe for the short term this suggestion isn't so important. thoughts?  i can just make a follow on ticket.

2023-04-13 04:00 UTC, nathanfranklin commented on README.md
> +Then add the jwt retreived from [Getting started](###getting-started) to `.env`.
```suggestion
Then add the jwt retrieved from [Getting started](###getting-started) to `.env`.
```

2023-04-13 04:01 UTC, nathanfranklin commented on README.md
> +#### Environments
good docs here 💯  👍

2023-04-27 03:05 UTC, nathanfranklin requested changes
Some additional comments to consider

I'm reaching out on slack about the use of .env in our two environments using the same image.

2023-04-28 17:59 UTC, sophia-massie approved these changes
LGTM! Thank you!!

2023-04-28 21:30 UTC, merged