Task/Add open in Taggit link
TACC-Cloud/hazmapper pull request #135
Opened 2023-04-18 18:30 UTC by duckonomy

## Overview: ##
Adds link to taggit for hazmapper.

## PR Status: ##

* [X] Ready.
* [ ] Work in Progress.
* [ ] Hold.

## Summary of Changes: ##
Adds link to hazmapper by utilizing taggit's `lastProj` stored in `localStorage` as subroutes seem to share `localStorage`.

## Testing Steps: ##
1. Unsure how to test locally at the moment... see **Notes**. However, observed behavior on production hazmapper/taggit.
 
## UI Photos:
<img width="315" alt="Screen Shot 2023-04-19 at 3 18 33 AM" src="https://user-images.githubusercontent.com/9425579/232867948-c0243899-bfcc-4d6e-a68a-74bdce7d7f23.png">

## Notes: ##
Related ticket: https://jira.tacc.utexas.edu/browse/WG-63
Currently as hazmapper and taggit are both hosted on same port, 4200,
there is no way to test shared behavior (e.g. linking between localStorage).

We might have to change port on taggit or hazmapper (this requires adding callbackUrl for that port).

Looking into this further, regarding `localStorage`, the values are not shared in subroutes if they have different ports (i.e. `localStorage` between http://localhost:4200 vs http://localhost:4201` is not shared).

We might have to just confirm the behavior on production and disregard this behavior locally unless we implement a workflow to serve hazmapper and taggit under same ports (via docker?)

There seem to be an issue on Taggit with the token not being invalidated properly from `localStorage` (and thus returning a 403)
Related to: https://github.com/taggit-tacc/taggit/pull/113#discussion_r1156557892
Possibly fixed with: https://github.com/taggit-tacc/taggit/pull/113/commits/b80c650db561889427f7805c476187dd35f36dc4

2023-04-21 15:20 UTC, sophia-massie approved these changes
LGTM with the added prefixes 👍

2023-04-26 03:34 UTC, nathanfranklin requested changes
Looks good to me.  👍  just two things to consider.

2023-04-26 03:34 UTC, nathanfranklin commented on angular/src/app/components/users-panel/users-panel.component.html
> +                    <button class="button hollow" (click)="openTaggit()">Open Map in Taggit</button>
what about: "Open map in Taggit" 


----------------


not for this PR but would good to have small Taggit logo in react version.

2023-04-27 02:37 UTC, nathanfranklin approved these changes
Excellent 👍

2023-04-28 17:25 UTC, merged