task/wg-75-project-listing-main
TACC-Cloud/hazmapper pull request #195
Opened 2024-01-12 22:50 UTC by sophia-massie

## Overview: ##

## PR Status: ##

* [X] Ready.
* [ ] Work in Progress.
* [ ] Hold.

## Related Jira tickets: ##

* [WG-XYZ](https://tacc-main.atlassian.net/browse/WG-XYZ)

## Summary of Changes: ##

## Testing Steps: ##
1. 

## UI Photos:

## Notes: ##

2024-01-17 22:49 UTC, tjgrafft reviewed
Tested locally and I see my correct project listings! Just one comment. When I load the page the ProjectListing component renders the first column 'Map' and its values right away, but the 'Project' column's values render after a slight delay. If I refresh the page the delay is still there. Looking at the network tab it takes 0.83 ms for the '/projects' request, while the /v2 request is taking 1.4 seconds. This could be causing the delay. Not sure, but maybe you can synchronize the rendering of the Map and Project columns by controlling their visibility based on the loading state of the asynchronous data

2024-01-17 22:51 UTC, sophia-massie commented
> Tested locally and I see my correct project listings! Just one comment. When I load the page the ProjectListing component renders the first column 'Map' and its values right away, but the 'Project' column's values render after a slight delay. If I refresh the page the delay is still there. Looking at the network tab it takes 0.83 ms for the '/projects' request, while the /v2 request is taking 1.4 seconds. This could be causing the delay. Not sure, but maybe you can synchronize the rendering of the Map and Project columns by controlling their visibility based on the loading state of the asynchronous data

Yes, definitely good catch. That is part of the follow on work I have to combine the response and track the state of both responses so that the table doesn't load until all the data is there.

2024-01-17 22:53 UTC, tjgrafft approved these changes

2024-01-18 15:53 UTC, nathanfranklin commented on react/src/components/Projects/ProjectListing.tsx
> +    return <h4>Unable to retrieve projects</h4>;
"maps" is preferred over "projects" in what the user sees on frontend (even though we use that term in Geoapi). Can we match what's currently in the angular client ([here](https://github.com/TACC-Cloud/hazmapper/blob/master/angular/src/app/components/main-welcome/main-welcome.component.html#L39C24-L44)) like the "Failed to Connect to Server" and possible error information? We added more details recently (see https://github.com/TACC-Cloud/hazmapper/pull/148) regarding the error as some accounts hit some strange behavior and helps us doing support.

2024-01-18 15:56 UTC, nathanfranklin commented on react/src/components/Projects/ProjectListing.tsx
> +import React from 'react';
Can a unit test for this be added?

2024-01-23 23:23 UTC, nathanfranklin requested changes
Looks good 👍  

 Here are some additional comments.  I also left some follow on ui-polishing/functionality on [slack](https://tacc-team.slack.com/archives/C04T8CKSWP5/p1705617510953699?thread_ts=1705100215.274389&cid=C04T8CKSWP5)

2024-01-29 16:18 UTC, nathanfranklin commented on react/src/types/projects.ts
> +}
new `transform` param would be a way to change the result and drop the `value` https://github.com/TACC-Cloud/hazmapper/blob/master/react/src/hooks/user/useAuthenticatedUser.ts#L10-L12

2024-03-15 18:42 UTC, taoteg commented on react/src/hooks/projects/useProjects.ts
> +export const useDsProjects =
second that =)

2024-03-15 18:44 UTC, taoteg reviewed
So far, looks good. 
Waiting for the edits Nathan requested before final review and approval.

2024-04-03 21:39 UTC, nathanfranklin approved these changes
LGTM 👍

2024-04-03 22:17 UTC, merged