branch task/WG-393-Asset-Detail-Pointclouds
TACC-Cloud/hazmapper pull request #296
Opened 2024-12-18 21:34 UTC by sophia-massie

## Overview: ##

Adds asset detail view for point clouds

## PR Status: ##

* [X] Ready.
* [ ] Work in Progress.
* [ ] Hold.

## Related Jira tickets: ##

* [WG-393](https://tacc-main.atlassian.net/browse/WG-393)

## Summary of Changes: ##
- Adds AssetPointCloud component
- Adds DOMPurify package to handle Pointclouds urls
- Strips args and memo logic from AssetRenderer
- Creates AssetButton component to handle what user do can per each file type and links/onClick

## Testing Steps: ##
1. Using prod environment locally, go to [Map: test_n0v9_2_delete](http://localhost:4200/project/6c273f81-6644-4958-9d8e-e358caded256)
2. Check that point cloud appears in asset detail
3. Check that View button opens point cloud in potree in a new window
4. Check that it looks the same as prod here [Prod Map: test_n0v9_2_delete](https://hazmapper.tacc.utexas.edu/hazmapper/project/6c273f81-6644-4958-9d8e-e358caded256)
5. Check other file types (img, movie, geometries, questionnaires) and make sure a View/Download/Add Asset button appears like prod. NOTE: only point cloud button should work atm

## UI Photos:
<img width="1263" alt="Screenshot 2024-12-18 at 3 33 02 PM" src="https://github.com/user-attachments/assets/f6607d9f-c181-4393-a742-f37571667832" />

## Notes: ##

Not sure that I love having the asset renderer declared and used in AssetDetail nor how the logic is laid out. Also open to suggestions on the AssetButton and what should be passed to it. 🙏

2025-01-07 21:58 UTC, nathanfranklin requested changes
LGTM. i have one small comment on variable names and then a suggestion on size of the image/point cloud preview.

2025-01-07 21:58 UTC, nathanfranklin commented on react/src/components/AssetDetail/AssetDetail.tsx
> +  const fileType: FeatureType = getFeatureType(selectedFeature);
```suggestion
  const featureType: FeatureType = getFeatureType(selectedFeature);
```
i would switch to the variable name to be clear; same suggestion applies to AssetButton

2025-01-07 21:58 UTC, nathanfranklin commented on react/src/components/AssetDetail/AssetDetail.tsx
> +          <AssetButton
> Not sure that I love having the asset renderer declared and used in AssetDetail nor how the logic is laid out. Also open to suggestions on the AssetButton and what should be passed to it

 All I can think of is putting the buttons inside AssetDetail to avoid having a switch case twice on featureType (and keeping things together like how AssetButton has  preview.html of point cloud and then AssetPointCloud has index.html of point cloud). 
 
 but really, its fine as is.  If we want, we can rethink it when we get to [Questionnaire](https://tacc-main.atlassian.net/issues/WG-389). Right now, it works fine as is 👍 .

2025-01-07 21:58 UTC, nathanfranklin commented on react/src/components/AssetDetail/AssetDetail.tsx
> +          <div className={styles.assetContainer}>
for point clouds, i think they need to take up more of the space.  and then for images, I see the download button appears in the middle before the image preview shows up.  i think if we added a width:100% and height:100% to assetContainer style that would fix those but then things would need to be tweaked so "This feature has no assets" has the right size.

2025-01-08 21:23 UTC, sophia-massie commented on react/src/components/AssetDetail/AssetDetail.tsx
> +          <div className={styles.assetContainer}>
This is updated. I did something a bit different than your suggestion to avoid stretching horizontal pictures or videos. Let me know what you think!

2025-01-08 22:53 UTC, nathanfranklin commented on react/src/components/AssetDetail/AssetDetail.tsx
> +          <div className={styles.assetContainer}>
awesome! looks good.

2025-01-08 23:02 UTC, nathanfranklin approved these changes
LGTM 👍

2025-01-09 18:55 UTC, merged