task/DES-1828 Streetview
TACC-Cloud/hazmapper pull request #45
Opened 2021-03-16 18:40 UTC by duckonomy

## Overview: ##

## PR Status: ##

* [ ] Ready.
* [X] Work in Progress.
* [ ] Hold.

## Related Jira tickets: ##

* [DES-1839](https://jira.tacc.utexas.edu/browse/DES-1839)
* [DES-1828](https://jira.tacc.utexas.edu/browse/DES-1828)
* [DES-1893](https://jira.tacc.utexas.edu/browse/DES-1893)

## Summary of Changes: ##
* [X] Authentication
  * [X] Authenticate to Mapillary
  * [X] Authenticate to Google (Not needed right now)
* [X] Create a progress notification to poll upload results.
  * [X] Implement retry logic 
  * [X] Create a separate model to include progress.
  * [X] Aggregate progress messages in the log.
* [X] Handle upload from tapis to geoapi.
  * [X] Implement retry logic
  * [X] Ensure images contain supported file data (e.g. GPano and Exif)
* [X] Handle upload from geoapi to tapis.
  * [X] Parse stdout of subprocess to get progress string. 
  * [X] Handle error from progress string.
* [X] Separate model to link mapillary sequences and tapis systems and paths.
* [X] Handle sequence data from mapillary. 
* [X] Pre/Post-processing for mapillary
* [ ] Expose more Mapillary APIs (e.g. changeset)
* [ ] Implement Google Streetview Upload
* [ ] ~~Abort mid-upload~~ There isn't a good way to undo once uploaded to mapillary
* [ ] Recursive uploads
* [X] ~~Handle pending approval~~ Done in Hazmapper

## Testing Steps: ##

## UI Photos:

## Notes: ##

2021-04-28 18:58 UTC, nathanfranklin requested changes
I'm still testing the linking and viewing the segments but wanted to provide some feedback.

Looking good.  👍 .  I really like workflow and how the user is provided with great progress information. 💯

2021-05-12 22:46 UTC, duckonomy commented on src/app/services/streetview.service.ts
> +  public getMapillaryImage(imageKey: string): any {
Yes 👍🏼

2021-05-12 22:49 UTC, duckonomy commented on src/app/components/streetview-assets/streetview-assets.component.html
> +          Uploading...
Switched to a spinner!

2021-05-12 22:53 UTC, duckonomy commented on src/app/components/modal-streetview-link/modal-streetview-link.component.html
> +          Loaded all sequences!
Added warning for empty sequences

2021-05-12 22:53 UTC, duckonomy commented on src/app/components/streetview-logs/streetview-logs.component.html
> +              Abort
Removed all retry-related things for now.

2021-05-13 22:32 UTC, duckonomy commented on src/app/components/map/map.component.ts
> +          this.map.setView(this.mapillarySequences.getBounds().getNorthEast(), 15);
I've changed this to `fitBounds`, which was what I was intending to get. For now, asset features and streetview features load separately. I wasn't sure what the best approach was to combine these.

2021-06-08 00:16 UTC, reptillicus commented on src/app/components/map/map.component.ts
> +        feat.setZIndex(1);
Is that needed?

2021-06-08 00:18 UTC, reptillicus commented on src/app/components/modal-streetview-publish/modal-streetview-publish.component.html
> +<!-- <h4>Select Where to Publish</h4>
Delete soon

2021-06-08 00:19 UTC, reptillicus commented on src/app/components/modal-streetview-link/modal-streetview-link.component.styl
> +        background-color: #D3D3D3
We've got #d3d3d3 as a variable in the base styles variables.

2022-04-18 16:47 UTC, nathanfranklin reviewed
I'm still working though testing but here are some initial comments/questions

2022-04-19 16:48 UTC, nathanfranklin commented on src/app/components/streetview-logs/streetview-logs.component.html
> +              Upload sucess!
```suggestion
              Upload success!
```

or maybe checkmark instead of text?

2022-04-22 02:52 UTC, nathanfranklin commented on src/app/services/streetview-authentication.service.ts
> +  }
unused; should be dropped

2022-04-22 02:53 UTC, nathanfranklin commented on src/app/services/streetview-authentication.service.ts
> +  }
unused and should be dropped;  looks like `deleteStreetviewByService` is what is used and supported in backend.

2022-04-22 02:54 UTC, nathanfranklin commented on src/app/services/streetview-authentication.service.ts
> +  }
```suggestion
```

unused; should be dropped.   looks like 'updateStreetviewByService` is what is used and supported in backend.

2022-04-22 02:54 UTC, nathanfranklin commented on src/app/services/streetview-authentication.service.ts
> +  }
unused and should be dropped;  looks like `deleteStreetviewByService` is what is used and supported in backend.
```suggestion

```

2022-04-22 03:20 UTC, nathanfranklin commented on src/app/services/streetview-authentication.service.ts
> +  }
Ignore above comment. lets discuss elsewhere

2022-04-22 03:20 UTC, nathanfranklin commented on src/app/services/streetview-authentication.service.ts
> +  }
Ignore above comment. lets discuss elsewhere

2022-04-27 15:04 UTC, nathanfranklin approved these changes
Excellent.  💯  🔥 

Just consider this [comment](https://github.com/TACC-Cloud/hazmapper/pull/45/files/2a9719febc9c339a82c8198d06a61083af1525b5#r851575857) before merging.

2022-04-27 15:42 UTC, merged