Add save to file functionality.
TACC-Cloud/hazmapper pull request #50
Opened 2021-04-08 23:02 UTC by duckonomy

## Overview: ##

## PR Status: ##

* [X] Ready.
* [ ] Work in Progress.
* [ ] Hold.

## Related Jira tickets: ##

* [DES-1929](https://jira.tacc.utexas.edu/browse/DES-1929)

## Summary of Changes: ##
Added a save button to the control-bar and a new project call to geoapi that save the file.

## Testing Steps: ##
0. Use the 
1. Create a project
2. Click the save button on the top left
3. Select a folder
4. Confirm that a `<uuid>.hazmapper` file of the current project is created. 

## UI Photos:
![HazMapper - Google Chrome_011](https://user-images.githubusercontent.com/9425579/114106510-880bf980-9894-11eb-86de-0431b9286538.png)

## Notes: ##

2021-05-14 17:20 UTC, nathanfranklin requested changes
Looks great!  Left some comments to consider.

Lots of my comments have suggestions for renaming things.  I'm not certain though if my suggestions are any good.  So I don't know if you (and @reptillicus ) consider what I wrote and if names need to be changed.  Or if we can poll Craig for his opinion.  Or just wait till we get feedback from Tracy.

2021-05-14 17:20 UTC, nathanfranklin commented on src/app/components/main-welcome/main-welcome.component.styl
> +  .list-column
could we make the `welcome-projects-list` wider (width:100%) and then maybe make these columns take up that space (but give less space to the 3rd column).  maybe a follow on ticket?

2021-05-14 17:20 UTC, nathanfranklin commented on src/app/components/modal-create-project/modal-create-project.component.html
> +          [allowedExtensions]="allowedExtensions"
is this change needed?

2021-05-14 17:20 UTC, nathanfranklin commented on src/app/components/modal-create-project/modal-create-project.component.ts
> +  fileSuffix: string = '';
should this be renamed to "fileName" or "fileBaseName" as the suffix is always "hazmapper".

2021-05-14 18:41 UTC, duckonomy commented on src/app/components/modal-link-project/modal-link-project.component.html
> +    <input #linkCheckbox type="checkbox"
I've checked it by default if the user is in a project folder.

2021-05-14 18:47 UTC, duckonomy commented on src/app/components/modal-create-project/modal-create-project.component.html
> +                <small><em>If name is not given, file will be saved as the map uuid.</em></small>
1. For the link modal, I can do that. But for the create project, I wouldn't have the UUID beforehand.
2. I will try doing this and create a separate Ticket/PR for that feature.

2021-05-14 18:49 UTC, duckonomy commented on src/app/components/users-panel/users-panel.component.html
> +        <a [href]="'https://www.designsafe-ci.org/data/browser/projects/' + activeProject.system_id + '/'"><span>{{activeProject.system_name}}</span></a>
I'm not sure where to get the PRJ-XXXX (as displayed in DS). The ID in tapis seemed to be a much longer one.

2021-05-14 20:27 UTC, nathanfranklin commented on src/app/components/users-panel/users-panel.component.html
> +        <a [href]="'https://www.designsafe-ci.org/data/browser/projects/' + activeProject.system_id + '/'"><span>{{activeProject.system_name}}</span></a>
It is in the projects response of https://agave.designsafe-ci.org//projects/v2/.  BUT yeah, that is probably not worth the effort at this stage (when we don't have Tracy feedback).  So maybe just ignore this comment.

2021-05-14 20:30 UTC, nathanfranklin commented on src/app/components/main-welcome/main-welcome.component.html
> +                        <span>{{p.system_name}}</span>
Ignore due to https://github.com/TACC-Cloud/hazmapper/pull/50#discussion_r632779256

2021-05-14 20:32 UTC, duckonomy commented on src/app/components/users-panel/users-panel.component.html
> +        <a [href]="'https://www.designsafe-ci.org/data/browser/projects/' + activeProject.system_id + '/'"><span>{{activeProject.system_name}}</span></a>
Gotcha!

2021-05-14 20:36 UTC, nathanfranklin commented on src/app/components/modal-create-project/modal-create-project.component.html
> +                <small><em>If name is not given, file will be saved as the map uuid.</em></small>
gotcha 👍

2021-05-14 21:37 UTC, duckonomy commented on src/app/components/users-panel/users-panel.component.html
> +        <a [href]="'https://www.designsafe-ci.org/data/browser/projects/' + activeProject.system_id + '/'"><span>{{activeProject.system_name}}</span></a>
Got this working!

2021-05-17 17:44 UTC, duckonomy commented on src/app/components/users-panel/users-panel.component.ts
> +    });
Should I handle it in the service function?

2021-05-17 18:19 UTC, duckonomy commented on src/app/services/projects.service.ts
> +      console.log(error);
I'll add a ticket for error handling. For now I added an error toast.

2021-05-18 12:58 UTC, reptillicus commented
Can we pull the "Make map public" button to the left and add a divider or something before the Export Map and Delete buttons ?

2021-05-28 22:28 UTC, nathanfranklin approved these changes
Looks good.  💯     The new layout of the Manage component looks very nice; a great improvement!

I think the few comments I have are very minor and can be stuck in a follow on ticket (and in some cases ignored). I guess take a look and see what you think.

2021-05-28 22:28 UTC, nathanfranklin commented on src/app/components/users-panel/users-panel.component.ts
> +    });
I see you handled it there 👍

2021-06-01 18:34 UTC, merged